name: Lint and Add Label on Pull Request

on:
  pull_request:
    types: [opened, synchronize, reopened]

permissions: write-all

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16' # Adjust the version as needed

      - name: Install dependencies
        run: npm install --force

      - name: Run Lint
        run: npm run lint # Assuming you have a "lint" script defined in your package.json

      - name: Add "Ready for Merging" label
        if: success() # Only runs if the linting step is successful
        uses: actions/github-script@v6
        with:
          script: |
            const pr = context.payload.pull_request;
            const prNumber = pr.number;
            const label = 'Ready for Merging';

            // Add the label to the PR
            await github.rest.issues.addLabels({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: prNumber,
              labels: [label],
            });
